const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  TOGGLE_USER_FETCHING: "TOGGLE_FETCHING",
  IS_FETCHING: "SET_IS_FETCHING",
  CLEAR_IS_FETCHING: "CLEAR_IS_FETCHING",
};

export default UserActionTypes;
